#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'lonelyinteger' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.


#---------------------------iMPORTANT-----------------------
#Al tner un limite de 100 datos, nosotros podemos facilmente crear un arreglo con 100 valores en 0 
#Despues recorrer el arreglo que se recibe y aumentar en 1 cada que valor del arreglo
#Al final obtendremos que solo un valor del arreglo de 100 valores tendra el valor de 1
#Solo debemos rettornar como respuesta la posicion que tenga como valor 1 y listo :D

def lonelyinteger(a):
    # Write your code here
    list0 = 100 * [0]
    res=0
    
    for i in range(len(a)):
        list0[a[i]] = list0[a[i]]+1
    
    
    for j in range(100):
        if list0[j] == 1:
            res = j
    return res

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = lonelyinteger(a)

    fptr.write(str(result) + '\n')

    fptr.close()
